name: flock
description: A social church management platform where identity belongs to people.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.38.0

dependencies:
  better_auth_flutter:
    path: packages/better_auth_flutter
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.8.0
  fpdart: ^1.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1

dependency_overrides:
  font_awesome_flutter:
    path: ../../font_awesome_flutter_pro

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
